ALTER TABLE shots
  DROP COLUMN IF EXISTS scene_id,
  DROP COLUMN IF EXISTS description,
  ADD COLUMN IF NOT EXISTS episode INTEGER NOT NULL DEFAULT 1,
  ADD COLUMN IF NOT EXISTS scene_no VARCHAR(50) NOT NULL DEFAULT '1',
  ADD COLUMN IF NOT EXISTS duration_sec INTEGER NOT NULL DEFAULT 1,
  ADD COLUMN IF NOT EXISTS aspect_ratio VARCHAR(30) NOT NULL DEFAULT '16:9',
  ADD COLUMN IF NOT EXISTS shot_size VARCHAR(30) NOT NULL DEFAULT '中景',
  ADD COLUMN IF NOT EXISTS camera_angle VARCHAR(30) NOT NULL DEFAULT '平视',
  ADD COLUMN IF NOT EXISTS action TEXT NOT NULL DEFAULT '',
  ADD COLUMN IF NOT EXISTS dialogue TEXT NOT NULL DEFAULT '',
  ADD COLUMN IF NOT EXISTS visual_requirements TEXT NOT NULL DEFAULT '',
  ADD COLUMN IF NOT EXISTS negative_prompt TEXT NOT NULL DEFAULT '',
  ADD COLUMN IF NOT EXISTS status VARCHAR(30) NOT NULL DEFAULT 'draft';
