ALTER TABLE generation_tasks
  ADD COLUMN IF NOT EXISTS provider VARCHAR(40) DEFAULT 'mock',
  ADD COLUMN IF NOT EXISTS request_params TEXT DEFAULT '',
  ADD COLUMN IF NOT EXISTS response_payload TEXT DEFAULT '',
  ADD COLUMN IF NOT EXISTS cost_estimate NUMERIC(12,6) DEFAULT 0,
  ADD COLUMN IF NOT EXISTS error_reason TEXT DEFAULT '';
