CREATE TABLE IF NOT EXISTS assets (
  id SERIAL PRIMARY KEY,
  project_id INTEGER,
  task_id INTEGER,
  asset_type VARCHAR(20) NOT NULL DEFAULT 'mock',
  provider VARCHAR(40) NOT NULL DEFAULT 'manual',
  title VARCHAR(200) NOT NULL DEFAULT '',
  description TEXT DEFAULT '',
  url TEXT DEFAULT '',
  local_path TEXT DEFAULT '',
  thumbnail_url TEXT DEFAULT '',
  prompt TEXT DEFAULT '',
  negative_prompt TEXT DEFAULT '',
  metadata TEXT DEFAULT '',
  status VARCHAR(20) NOT NULL DEFAULT 'draft',
  created_at TIMESTAMPTZ DEFAULT NOW(),
  updated_at TIMESTAMPTZ DEFAULT NOW()
);

ALTER TABLE assets ADD COLUMN IF NOT EXISTS project_id INTEGER;
ALTER TABLE assets ADD COLUMN IF NOT EXISTS task_id INTEGER;
ALTER TABLE assets ADD COLUMN IF NOT EXISTS asset_type VARCHAR(20) NOT NULL DEFAULT 'mock';
ALTER TABLE assets ADD COLUMN IF NOT EXISTS provider VARCHAR(40) NOT NULL DEFAULT 'manual';
ALTER TABLE assets ADD COLUMN IF NOT EXISTS title VARCHAR(200) NOT NULL DEFAULT '';
ALTER TABLE assets ADD COLUMN IF NOT EXISTS description TEXT DEFAULT '';
ALTER TABLE assets ADD COLUMN IF NOT EXISTS url TEXT DEFAULT '';
ALTER TABLE assets ADD COLUMN IF NOT EXISTS local_path TEXT DEFAULT '';
ALTER TABLE assets ADD COLUMN IF NOT EXISTS thumbnail_url TEXT DEFAULT '';
ALTER TABLE assets ADD COLUMN IF NOT EXISTS prompt TEXT DEFAULT '';
ALTER TABLE assets ADD COLUMN IF NOT EXISTS negative_prompt TEXT DEFAULT '';
ALTER TABLE assets ADD COLUMN IF NOT EXISTS metadata TEXT DEFAULT '';
ALTER TABLE assets ADD COLUMN IF NOT EXISTS status VARCHAR(20) NOT NULL DEFAULT 'draft';
ALTER TABLE assets ADD COLUMN IF NOT EXISTS created_at TIMESTAMPTZ DEFAULT NOW();
ALTER TABLE assets ADD COLUMN IF NOT EXISTS updated_at TIMESTAMPTZ DEFAULT NOW();
